# Generated by Django 3.0.2 on 2020-02-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id_cajero', models.AutoField(db_column='ID_CAJERO', primary_key=True, serialize=False)),
                ('nombre_cajero', models.CharField(db_column='NOMBRE_CAJERO', max_length=15)),
                ('clave_cajero', models.CharField(db_column='CLAVE_CAJERO', max_length=15)),
                ('estado_cajero', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], db_column='ESTADO_CAJERO', default='activo', max_length=10)),
            ],
            options={
                'db_table': 'CAJERO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CartonCartas',
            fields=[
                ('id_c_c', models.AutoField(db_column='ID_C_C', primary_key=True, serialize=False)),
                ('alta_baja', models.TextField(db_column='ALTA_BAJA')),
                ('color', models.TextField(db_column='COLOR')),
                ('valor_apuesta_c', models.IntegerField(db_column='VALOR_APUESTA_C')),
                ('fecha_cartas', models.DateField(db_column='FECHA_CARTAS')),
                ('hora_cartas', models.TimeField(db_column='HORA_CARTAS')),
            ],
            options={
                'db_table': 'CARTON_CARTAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CartonKeno',
            fields=[
                ('id_c_k', models.AutoField(db_column='ID_C_K', primary_key=True, serialize=False)),
                ('apuesta_keno', models.TextField(db_column='APUESTA_KENO')),
                ('valor_apuesta_k', models.IntegerField(db_column='VALOR_APUESTA_K')),
                ('fecha_keno', models.DateField(db_column='FECHA_KENO')),
                ('hora_keno', models.TimeField(db_column='HORA_KENO')),
            ],
            options={
                'db_table': 'CARTON_KENO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GanadoresCartas',
            fields=[
                ('id_ganadores_c', models.AutoField(db_column='ID_GANADORES_C', primary_key=True, serialize=False)),
                ('valor_ganado_c', models.IntegerField(db_column='VALOR_GANADO_C')),
                ('fecha_ganadores_c', models.DateField(db_column='FECHA_GANADORES_C')),
                ('hora_ganadores_c', models.TimeField(db_column='HORA_GANADORES_C')),
            ],
            options={
                'db_table': 'GANADORES_CARTAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GanadoresJackpot',
            fields=[
                ('id_ganadores_j', models.AutoField(db_column='ID_GANADORES_J', primary_key=True, serialize=False)),
                ('valor_ganado_j', models.IntegerField(db_column='VALOR_GANADO_J')),
                ('fecha_ganadores_j', models.DateField(db_column='FECHA_GANADORES_J')),
                ('hora_ganadores_j', models.TimeField(db_column='HORA_GANADORES_J')),
                ('id_c_k', models.IntegerField(db_column='ID_C_K')),
            ],
            options={
                'db_table': 'GANADORES_JACKPOT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GanadoresKeno',
            fields=[
                ('id_ganadores_k', models.AutoField(db_column='ID_GANADORES_K', primary_key=True, serialize=False)),
                ('valor_ganado_k', models.IntegerField(db_column='VALOR_GANADO_K')),
                ('fecha_ganadores_k', models.DateField(db_column='FECHA_GANADORES_K')),
                ('hora_ganadores_k', models.TimeField(db_column='HORA_GANADORES_K')),
                ('id_c_k', models.IntegerField(db_column='ID_C_K')),
            ],
            options={
                'db_table': 'GANADORES_KENO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jackpot',
            fields=[
                ('id_jackpot', models.AutoField(db_column='ID_JACKPOT', primary_key=True, serialize=False)),
                ('monto_actual', models.IntegerField(db_column='MONTO_ACTUAL')),
                ('monto_activacion_j', models.IntegerField(db_column='MONTO_ACTIVACION_J')),
                ('activacion_bono', models.IntegerField(db_column='ACTIVACION_BONO')),
                ('fecha_jackpot', models.DateField(db_column='FECHA_JACKPOT')),
                ('hora_jackpot', models.TimeField(db_column='HORA_JACKPOT')),
            ],
            options={
                'db_table': 'JACKPOT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.AutoField(db_column='ID_LOCALIDAD', primary_key=True, serialize=False)),
                ('nombre_localidad', models.CharField(db_column='NOMBRE_LOCALIDAD', max_length=15)),
            ],
            options={
                'db_table': 'LOCALIDAD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PosPc',
            fields=[
                ('id_pos_pc', models.AutoField(db_column='ID_POS_PC', primary_key=True, serialize=False)),
                ('codigo_pos_pc', models.IntegerField(db_column='CODIGO_POS_PC')),
                ('estado_pos_pc', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], db_column='ESTADO_POS_PC', default='activo', max_length=10)),
            ],
            options={
                'db_table': 'POS_PC',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('id_pv', models.AutoField(db_column='ID_PV', primary_key=True, serialize=False)),
                ('nombre_pv', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_pv', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], db_column='ESTADO_PV', default='activo', max_length=10)),
                ('localidad', models.CharField(db_column='LOCALIDAD', max_length=25)),
            ],
            options={
                'db_table': 'PUNTO_VENTA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sorteos',
            fields=[
                ('id_sorteos', models.AutoField(db_column='ID_SORTEOS', primary_key=True, serialize=False)),
                ('numeros_sorteos', models.IntegerField(db_column='NUMEROS_SORTEOS')),
                ('bonos', models.TextField(db_column='BONOS')),
                ('carta_ganadora', models.IntegerField(db_column='CARTA_GANADORA')),
                ('fecha_sorteos', models.DateField(db_column='FECHA_SORTEOS')),
                ('hora_sorteos', models.TimeField(db_column='HORA_SORTEOS')),
                ('estado_sorteos', models.TextField(db_column='ESTADO_SORTEOS')),
                ('numero_carta', models.IntegerField(db_column='NUMERO_CARTA')),
            ],
            options={
                'db_table': 'SORTEOS',
                'managed': False,
            },
        ),
    ]
